---
title: "Replication, Estimator Performance: homogenous treatment effect model"
author: "[Christophe Bruneel-Zupanc](https://www.cbruneel.com/)"
date: "Last modified: 2024-07-22"
output:
  rmarkdown::html_document:
    toc: true
    toc_depth: 2
  rmarkdown::html_vignette:
    highlight: monochrome
    toc: true
  pdf_document:
    highlight: monochrome
bibliography: semiIVreg.bib
biblio-style: "apalike"
vignette: >
  %\VignetteKeywords{instrumental variables, semi-IVs, causal inference}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Replication, Estimator Performance: homogenous treatment effect model}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", echo = TRUE, fig.retina = 2#,#fig.height=4, fig.width=5, fig.align='center'
)
if (!requireNamespace("ivreg", quietly = TRUE)) {
  install.packages("ivreg")
}
library(ivreg); library(semiIVreg)
options(scipen=8)
```




The code below provides the code to run to replicate the Heterogenous treatment effect simulations of @bruneel2024. 
For an exact replication, increase the number of Monte Carlo simulations to 500 (here, `N_simul=50` for pace). 


## General Model with Heterogenous Treatment Effects

```{r mc} 
# 0. Model Specification
# ----------------------
N_MC = 50; # number of monte carlo
N = 10000; # Number of observations per MC simulations

set.seed(1234)

# Specification
model_type = "heterogenous"
param_error = c(1, 1.5, 0.5, 1.5) # var_u0, var_u1, cov_u0u1, var_cost (the mean cost = constant in D*) # if heterogenous
param_Z = c(0, 0, 0, 0, 1, 0.8, 0.3) # meanW0 state0, meanW1 state0, meanW0 state1, meanW1 state1, varW0, varW1, covW0W1
param_p = c(-0.2, -1.2, 1, 0, 0, 0) # constant, alphaW0, alphaW1, alphaW0W1, effect of state, effect of parent educ
param_y0 = c(3.2, 1, 0, 0) # intercept, effect of Wd, effect of state, effect of parent educ;
param_y1 = c(3.2+0.4, 1.3, 0, 0) # the +0.2 = Average treatment effect; effect of W1, effect of state, effect of parent educ;
param_genX = c(0.4, 0, 2)

# Underlying true MTE and MTR:
seq_p = seq(0, 1, by=0.001);
w0 = 0; w1 = 0;
sigma_V2 = param_error[1] + param_error[2] - 2*param_error[3] + param_error[4] # = var(V); var(data$V)
covU0V = param_error[1] - param_error[3] # = cov(data$U0, data$V)
covU1V = -param_error[2] + param_error[3] # = cov(data$U1, data$V)
ku0 = covU0V/sigma_V2*(qnorm(seq_p, mean=0, sd=sqrt(sigma_V2)) - 0) # 0 = mean(V)
ku1 = covU1V/sigma_V2*(qnorm(seq_p, mean=0, sd=sqrt(sigma_V2)) - 0) # 0 = mean(V)
true_mtr0 = param_y0[1] + param_y0[2]*w0 + ku0
true_mtr1 = param_y1[1] + param_y1[2]*w1 + ku1
true_mte = true_mtr1 - true_mtr0
newdata = data.frame(Ud=seq_p, w0=0, w1=0)
newdata$true_mte = true_mte; newdata$true_mtr1 = true_mtr1; newdata$true_mtr0 = true_mtr0

```



to finish
